server:
  port: 8081

spring:
  application:
    name: hexagonal
  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

ramonmoncao:
  client:
    address:
      url: http://localhost:8082/addresses
